name: Segrep Scan

on: 
   push: 
       branches: [ main ]
   pull_request: 
       branches: [ main ]

jobs: 
   semgrep:
       runs-on: ubuntu-latest

       steps: 
          - name: Install Semgrep
             run: pip install semgrep

          - name: Run Semgrep scan
             run: segrep scan --config=auto
