name: Segrep Scan

on: 
   push: 
       branches: [ main ]
   pull_request: 
       branches: [ main ]

jobs: 
   semgrep:
       runs-on: ubuntu-latest

       steps: 
          - name: Run Semgrep scan
            run: semgrep ci --config=auto
            env: 
                SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN}}
